# Generated by Django 6.0.7 on 2026-07-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_stock_buy_price_stock_purchase_date_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=20),
        ),
    ]
