# Generated by Django 6.0.7 on 2026-07-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_stock_buy_price_alter_stock_purchase_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='purchase_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
